# Generated by Django 4.2.11 on 2024-11-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltbohotel',
            name='rating',
            field=models.CharField(max_length=10),
        ),
    ]
